import type { WorkshopStep } from "@/lib/workshop/types";

export const WORKSHOP_STEPS: WorkshopStep[] = [
  {
    id: "welcome",
    slideRef: "Slide 1",
    title: "Bienvenue dans l'atelier vente",
    subtitle: "Une lecture simple, concrete et terrain.",
    intro:
      "Tu vas construire ton propre support de vente au fil du cours. L'objectif n'est pas de faire joli, mais de rendre ton prochain entretien plus clair, plus structure et plus naturel.",
    coachCue:
      "Reste concret. L'atelier sert a fabriquer des formulations utiles pour tes rendez-vous, pas a raconter toute l'histoire de ta startup.",
    railTitle: "Repere de demarrage",
    railBullets: [
      "Tu notes uniquement ce qui te sera utile en entretien.",
      "Tu peux revenir en arriere a tout moment.",
      "Les boutons IA servent a clarifier tes notes, pas a faire l'exercice a ta place.",
    ],
    fields: [],
  },
  {
    id: "opening-question",
    slideRef: "Slide 2",
    title: "Question d'ouverture",
    subtitle: "Faire emerger ta representation de la vente.",
    intro:
      "Prends quelques minutes pour poser ta propre lecture de la vente avant d'adopter une structure commune.",
    coachCue:
      "Ta reponse peut rester imparfaite. Le but est de partir de ta vision actuelle pour la rendre plus solide ensuite.",
    railTitle: "Questions a te poser",
    railBullets: [
      "Ou commence la vente pour toi ?",
      "Jusqu'ou va-t-elle ?",
      "Quelles etapes te semblent indispensables ?",
    ],
    fields: [
      {
        id: "openingReflection",
        label: "Ta reponse a la question d'ouverture",
        helper:
          "Note ta vision spontanée : debut, fin et grandes etapes de la vente.",
        placeholder:
          "Pour moi, la vente commence quand... Elle va jusqu'a... Les etapes sont...",
        kind: "textarea",
        rows: 7,
        aiActions: ["clarify", "shorten", "flag_vagueness"],
      },
    ],
  },
  {
    id: "interview-pyramid",
    slideRef: "Slide 3",
    title: "Architecture de l'entretien",
    subtitle: "Les 5 etages de la pyramide.",
    intro:
      "La vente suit une sequence logique. Plus la base est solide, plus la suite devient naturelle.",
    coachCue:
      "Ne cherche pas a tout remplir d'un coup. Note surtout les points qui te paraissent critiques a chaque etage.",
    railTitle: "La logique de la pyramide",
    railBullets: [
      "Pas de bon closing sans de bonnes bases.",
      "Chaque etage a un objectif distinct.",
      "Tu dois savoir ce que tu veux obtenir a chaque moment de l'entretien.",
    ],
    fields: [
      {
        id: "contact",
        label: "Prise de contact",
        helper: "Que veux-tu absolument reussir dans les premieres minutes ?",
        placeholder: "Installer le lien, cadrer l'echange, montrer que...",
        kind: "textarea",
        rows: 4,
        aiActions: ["clarify", "shorten", "flag_vagueness"],
      },
      {
        id: "discovery",
        label: "Decouverte",
        helper:
          "Quelles informations dois-tu faire emerger pour comprendre la situation du client ?",
        placeholder: "Je dois comprendre ou ils en sont, ce qui coince, ce qui compte...",
        kind: "textarea",
        rows: 4,
        aiActions: ["clarify", "shorten", "flag_vagueness"],
      },
      {
        id: "argumentation",
        label: "Argumentation",
        helper: "Comment relies-tu les besoins du prospect a ta valeur ?",
        placeholder: "Je relie leur enjeu a notre solution en montrant...",
        kind: "textarea",
        rows: 4,
        aiActions: ["clarify", "shorten", "flag_vagueness"],
      },
      {
        id: "objections",
        label: "Objections",
        helper: "Quels freins veux-tu savoir traiter sans casser la dynamique ?",
        placeholder: "Je dois savoir repondre sur le temps, le risque, le budget...",
        kind: "textarea",
        rows: 4,
        aiActions: ["clarify", "shorten", "flag_vagueness"],
      },
      {
        id: "closing",
        label: "Closing",
        helper:
          "Quel engagement clair veux-tu obtenir en fin d'entretien ?",
        placeholder: "Obtenir un prochain pas concret, date, test, mise en relation...",
        kind: "textarea",
        rows: 4,
        aiActions: ["clarify", "shorten", "flag_vagueness"],
      },
    ],
  },
  {
    id: "roleplay-1",
    slideRef: "Slide 4",
    title: "Premiere mise en situation",
    subtitle: "Preparer ton demarrage d'entretien.",
    intro:
      "Ici, tu te pretes mentalement au jeu avant la pratique. L'objectif est de demarrer, cadrer, credibiliser et basculer vers la premiere question de decouverte.",
    coachCue:
      "Fais simple. Une bonne entree en matiere est souvent courte, propre et calme.",
    railTitle: "A preparer",
    railBullets: [
      "Comment tu arrives et tu lances l'echange.",
      "Ton pitch tres court avant la decouverte.",
      "La premiere question qui ouvre vraiment la discussion.",
    ],
    fields: [
      {
        id: "roleplayPrep",
        label: "Preparation avant la mise en situation",
        helper: "Ce que tu veux dire ou faire dans les 60 premieres secondes.",
        placeholder: "Je veux commencer par..., puis enchaine sur..., puis poser...",
        kind: "textarea",
        rows: 6,
        aiActions: ["clarify", "shorten", "oralize_30s"],
      },
      {
        id: "roleplayDebrief",
        label: "Notes apres la mise en situation",
        helper: "Ce que tu retiens, ce que tu veux garder, ce que tu veux corriger.",
        placeholder: "Ce qui a marche..., ce que je veux corriger..., ma vigilance pour la suite...",
        kind: "textarea",
        rows: 6,
        aiActions: ["clarify", "shorten", "flag_vagueness"],
      },
    ],
  },
  {
    id: "contact-builder",
    slideRef: "Slides 5-6",
    title: "Construire ta prise de contact",
    subtitle: "Bris de glace, cadre, plan, timing, validation, pitch et premiere question.",
    intro:
      "Tu vas produire une version utilisable de ta prise de contact, directement exploitable en rendez-vous.",
    coachCue:
      "Le bris de glace se personnalise. Le cadre, le plan, le timing et la validation doivent eux rester simples et robustes.",
    railTitle: "Ce que doit envoyer ta prise de contact",
    railBullets: [
      "Humanite : la relation d'abord.",
      "Organisation : tu structures l'echange.",
      "Competence : tu legitimises la suite.",
    ],
    fields: [
      {
        id: "icebreaker",
        label: "Bris de glace personnalise",
        helper: "Une entree naturelle, adaptee a la personne et au contexte.",
        placeholder: "Bonjour..., merci de prendre ce temps..., j'ai vu que...",
        kind: "textarea",
        rows: 4,
        aiActions: ["clarify", "shorten", "oralize_30s"],
      },
      {
        id: "cadre",
        label: "Cadre",
        helper: "La raison claire de votre echange aujourd'hui.",
        placeholder: "La raison pour laquelle nous nous rencontrons aujourd'hui est...",
        kind: "textarea",
        rows: 3,
        aiActions: ["clarify", "shorten", "oralize_30s"],
      },
      {
        id: "plan",
        label: "Plan",
        helper: "Comment tu annonces le deroule de l'entretien.",
        placeholder:
          "Je vais vous presenter rapidement ma startup puis surtout etudier votre situation...",
        kind: "textarea",
        rows: 4,
        aiActions: ["clarify", "shorten", "oralize_30s"],
      },
      {
        id: "timing",
        label: "Timing",
        helper: "La duree annoncee de facon simple et rassurante.",
        placeholder: "Tout cela devrait prendre environ 45 minutes.",
        kind: "textarea",
        rows: 2,
        aiActions: ["clarify", "shorten"],
      },
      {
        id: "validation",
        label: "Validation",
        helper: "Le petit oui qui aligne le terrain avant d'aller plus loin.",
        placeholder: "Est-ce que cela vous convient ? C'est bon pour vous ?",
        kind: "textarea",
        rows: 2,
        aiActions: ["clarify", "shorten"],
      },
      {
        id: "pitch",
        label: "Pitch de prise de contact",
        helper: "Un pitch court, lisible, centre sur l'enjeu traite.",
        placeholder: "Nous developpons une solution qui aide... a mieux...",
        kind: "textarea",
        rows: 5,
        aiActions: [
          "clarify",
          "shorten",
          "variants_3",
          "oralize_30s",
          "oralize_60s",
        ],
      },
      {
        id: "firstDiscoveryQuestion",
        label: "Premiere question de decouverte",
        helper: "La question qui ouvre reellement la discussion.",
        placeholder: "Aujourd'hui, comment gerez-vous ce sujet ?",
        kind: "textarea",
        rows: 3,
        aiActions: ["clarify", "shorten", "variants_3"],
      },
    ],
  },
  {
    id: "startup-strengths",
    slideRef: "Slide 7",
    title: "Les forces de ta startup",
    subtitle: "Clarifier ce qui rend ton projet solide.",
    intro:
      "Avant de construire un pitch credibilisant, clarifie ce que tu sais deja faire et ce qui rend ton projet legitime.",
    coachCue:
      "Liste des elements concrets, pas des promesses vagues. Le critere, c'est la credibilite percue par un interlocuteur serieux.",
    railTitle: "Les 4 questions a remplir",
    railBullets: [
      "Ce que vous savez deja bien faire.",
      "Ce que vous allez bien savoir faire.",
      "La ou votre startup sera performante.",
      "Ce qui rend votre projet credible.",
    ],
    fields: [
      {
        id: "alreadyDoWell",
        label: "Ce que vous savez deja bien faire",
        helper: "Expertise, experience, comprehension du terrain, savoir-faire actuel.",
        placeholder: "Nous savons deja bien faire...",
        kind: "textarea",
        rows: 5,
        aiActions: ["clarify", "shorten", "flag_vagueness"],
      },
      {
        id: "willDoWell",
        label: "Ce que vous allez bien savoir faire",
        helper: "La promesse forte de ta startup.",
        placeholder: "Notre solution va nous permettre de tres bien...",
        kind: "textarea",
        rows: 5,
        aiActions: ["clarify", "shorten", "flag_vagueness"],
      },
      {
        id: "futurePerformance",
        label: "La ou votre startup sera performante",
        helper: "Execution, simplicite, personnalisation, reactivite, fiabilite...",
        placeholder: "Nous pensons etre particulierement forts sur...",
        kind: "textarea",
        rows: 5,
        aiActions: ["clarify", "shorten", "flag_vagueness"],
      },
      {
        id: "credibility",
        label: "Ce qui rend votre projet credible",
        helper: "Parcours, connaissance terrain, tests, retours, premiers signaux.",
        placeholder: "Ce qui donne du poids a notre demarche, c'est...",
        kind: "textarea",
        rows: 5,
        aiActions: ["clarify", "shorten", "flag_vagueness"],
      },
    ],
  },
  {
    id: "client-issues",
    slideRef: "Slide 8",
    title: "Les enjeux de tes interlocuteurs",
    subtitle: "Parler d'eux avant de parler de toi.",
    intro:
      "Un pitch solide part des attentes, tensions et difficultes de la personne en face.",
    coachCue:
      "Cherche ce qu'ils veulent obtenir, eviter, securiser ou ameliorer. C'est souvent la que se trouve la meilleure matiere pour ton pitch.",
    railTitle: "Les 4 questions a clarifier",
    railBullets: [
      "Ce qu'ils veulent obtenir ou ameliorer.",
      "Ce qui les freine aujourd'hui.",
      "Ce qui est vraiment important pour eux.",
      "Ce qu'ils cherchent a obtenir ou a eviter.",
    ],
    fields: [
      {
        id: "clientGoals",
        label: "Ce que les clients veulent obtenir ou ameliorer",
        helper: "Temps, visibilite, securite, resultat, simplicite...",
        placeholder: "Mes interlocuteurs cherchent a obtenir ou ameliorer...",
        kind: "textarea",
        rows: 5,
        aiActions: ["clarify", "shorten", "flag_vagueness"],
      },
      {
        id: "clientFriction",
        label: "Ce qui les freine aujourd'hui",
        helper: "Temps, complexite, dispersion, manque de methode, ressources...",
        placeholder: "Ce qui les freine le plus aujourd'hui, c'est...",
        kind: "textarea",
        rows: 5,
        aiActions: ["clarify", "shorten", "flag_vagueness"],
      },
      {
        id: "clientPriorities",
        label: "Ce qui est important pour eux",
        helper: "Efficacite, securite, image, conformite, rentabilite...",
        placeholder: "Ce qui compte vraiment pour eux, c'est...",
        kind: "textarea",
        rows: 5,
        aiActions: ["clarify", "shorten", "flag_vagueness"],
      },
      {
        id: "clientRisks",
        label: "Ce qu'ils veulent obtenir ou eviter",
        helper: "Le resultat vise ou le probleme a eviter.",
        placeholder: "Ils cherchent a obtenir..., ou a eviter...",
        kind: "textarea",
        rows: 5,
        aiActions: ["clarify", "shorten", "flag_vagueness"],
      },
    ],
  },
  {
    id: "value-and-pitch",
    slideRef: "Slides 9-11",
    title: "Valeur ajoutee et pitch",
    subtitle: "Relier ta reponse, ses benefices et une version orale claire.",
    intro:
      "A partir des enjeux deja formules, tu vas maintenant montrer ce que ta startup apporte de concret et ce que cela permet reellement.",
    coachCue:
      "Reste lisible. D'abord l'enjeu, ensuite la reponse, puis le benefice. Le pitch court doit donner envie d'aller plus loin, pas tout raconter.",
    railTitle: "Ton fil directeur",
    railBullets: [
      "Ce que vous apportez concretement.",
      "Ce que cela permet reellement.",
      "Une version orale courte et impactante.",
    ],
    fields: [
      {
        id: "valueResponse",
        label: "Ce que vous apportez",
        helper: "Solution, methode, savoir-faire, technologie ou accompagnement.",
        placeholder: "Pour repondre a ces enjeux, nous apportons...",
        kind: "textarea",
        rows: 5,
        aiActions: ["clarify", "shorten", "flag_vagueness", "variants_3"],
      },
      {
        id: "valueMethod",
        label: "Comment vous traitez le sujet",
        helper: "Plus simple, plus fluide, plus rapide, plus fiable...",
        placeholder: "Notre maniere de traiter ce sujet est...",
        kind: "textarea",
        rows: 4,
        aiActions: ["clarify", "shorten", "flag_vagueness"],
      },
      {
        id: "valueBenefits",
        label: "Ce que cela permet",
        helper: "Gagner, eviter, securiser, ameliorer.",
        placeholder: "Cela permet a nos interlocuteurs de gagner..., d'eviter..., de securiser...",
        kind: "textarea",
        rows: 5,
        aiActions: ["clarify", "shorten", "flag_vagueness", "variants_3"],
      },
      {
        id: "pitch30",
        label: "Pitch court 30 secondes",
        helper: "Une version ramassee, tres claire, utilisable vite.",
        placeholder: "Nous aidons [type d'interlocuteur] qui font face a...",
        kind: "textarea",
        rows: 5,
        aiActions: [
          "clarify",
          "shorten",
          "variants_3",
          "oralize_30s",
          "flag_vagueness",
        ],
      },
      {
        id: "pitch60",
        label: "Pitch oral 1 minute max",
        helper: "Une version orale plus posee, mais toujours lisible.",
        placeholder: "En une minute, je presenterais ma startup ainsi...",
        kind: "textarea",
        rows: 6,
        aiActions: ["clarify", "shorten", "oralize_60s", "flag_vagueness"],
      },
    ],
  },
  {
    id: "final-playbook",
    slideRef: "Slide 12",
    title: "Ton playbook final",
    subtitle: "Une synthese nette, copiable et printable.",
    intro:
      "Cette derniere etape assemble automatiquement ta prise de contact, tes forces, les enjeux client, ta proposition de valeur et ton pitch.",
    coachCue:
      "Relis a voix haute. Le meilleur support est celui que tu peux vraiment utiliser demain.",
    railTitle: "A la fin de l'atelier",
    railBullets: [
      "Tu repars avec une base de prise de contact exploitable.",
      "Tu peux copier, imprimer ou rouvrir ton playbook.",
      "Tu gardes un lien personnel de reprise.",
    ],
    fields: [
      {
        id: "commitmentNote",
        label: "Ton engagement personnel pour le prochain entretien",
        helper: "Une decision concrete sur ce que tu veux faire differemment.",
        placeholder: "Lors de mon prochain entretien, je veux absolument...",
        kind: "textarea",
        rows: 4,
        aiActions: ["clarify", "shorten", "oralize_30s"],
      },
    ],
  },
];

export function getWorkshopStep(stepId: string) {
  return WORKSHOP_STEPS.find((step) => step.id === stepId) ?? WORKSHOP_STEPS[0];
}
